### ISSUE TITLE
Port nessdb driver from https://github.com/pmwkaa/ioarena

### ISSUE THREAD

**Issue by leo-yuriev** [ReOpen/ioarena2#1]
Can anyone do this?

@BohuTANG ?

**Comment by BohuTANG** [comment]
Hello,
I 'll be happy to do it when I have time.

**Comment by BohuTANG** [comment]
e, 
what's the differences between pmwkaa/ioarena and ReOpen/ioarena2?
From the help, I don't see the point.

**Comment by leo-yuriev** [comment]
Currently I haven't updated the README. In general the differences are (from description of repo):
> To provide multithreading and isolation from the testcases the **interface of a DB drivers cardinally redesigned**. In the IoArena2 it is clear and intelligible.

**Comment by leo-yuriev** [comment]
Moved to https://github.com/pmwkaa/ioarena/issues/8
